apiVersion: v1  
kind: Secret
metadata:
  name: mysql-secret  
type : Opaque
stringData:
  MYSQL_ROOT_PASSWORD: changen-me-root-password
  MYSQL_DATABASE: app-db
  MYSQL_USER: laravel
  MYSQL_PASSWORD: supersecretpassword

  