apiVersion: v1
kind: Secret
metadata:
  name: laravel-env-secret
type: Opaque
stringData:
  APP_KEY: base64:UmN6Gvr4mL9hsuq5OMebzNdNYxwfVCsI/b7hmVC8JiM=
  APP_ENV: production
  APP_NAME: Laravel

  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: app-db
  DB_USERNAME: laravel
  DB_PASSWORD: supersecretpassword
  CACHE_DRIVER: redis
  QUEUE_CONNECTION: redis
  SESSION_DRIVER: redis

  REDIS_HOST: redis
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"
  REDIS_CLIENT: predis

