apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: laravel-nginx-config

        - name: app-code
          emptyDir: {}

      ########################################
      # 🔥 initContainer: ينسخ كود Laravel
      ########################################
      initContainers:
        - name: copy-app
          image: 902085629324.dkr.ecr.us-east-2.amazonaws.com/laravel-app-k8s:latest
          command:
            - sh
            - -c
            - |
              echo "Copying Laravel app..." ;
              cp -R /var/www/html/* /var/www/ ;
              cp -R /var/www/html/.[!.]* /var/www/ 2>/dev/null || true ;
              echo "Copy done."
          volumeMounts:
            - name: app-code
              mountPath: /var/www

      ########################################
      # 🔥 Laravel / PHP-FPM
      ########################################
      containers:
        - name: laravel
          image: 902085629324.dkr.ecr.us-east-2.amazonaws.com/laravel-app-k8s:latest
          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: laravel-env-secret

          command: ["php-fpm", "-F"]

          volumeMounts:
            - name: app-code
              mountPath: /var/www

          ports:
            - containerPort: 9000

          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5

          startupProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5

        ########################################
        # 🔥 NGINX
        ########################################
        - name: nginx
          image: nginx:alpine

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: app-code
              mountPath: /var/www

          ports:
            - containerPort: 80

          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
          startupProbe:
            httpGet:
              path: /health/startup
              port: 80
